---

# test playbook for rconf

name: "Update and install Nginx on webservers"
targets: "webservers"
jobs:
  - name: "Update package cache (apt update)"
    rconf:apt:
      run: "update"
      
  - name: "Install Nginx server"
    rconf:apt:
      run: "install"
      package: "nginx"